### ISSUE TITLE
Unexpected token error when running the npx command

### ISSUE THREAD

**Issue by thejoelinux** [jsimck/jsconfig.json#2] opened 2021-03-07 10:13 UTC
Hi,

I installed the package in my VueJS project, but when i run the `npx jsconfig.json .` command as the README says, it stops on error:
```
Unexpected token .
```
No files are created.
My development environment is on Ubuntu 20.10; 
```
npm --version
6.14.10
```

Is there anything more you need ?

Regards,
Denis

**Comment by jsimck** [comment] 2021-03-08 19:16
Hi,

thank you for your interest in this tool. It was released some time ago as a very early "working concept" which would then be expanded upon (unfortunately accidentally without `beta` tag). Sadly I really didn't have any free time to continue working on it so basically it's currently released in not a very healthy condition.

I've just released really quickly refactored version `0.1.0-beta.5`, which hopefully fixes some potential issues so you may try that. I will hopefully finish first working RC by the end if the week, which should be much more stable and support older versions of node. Currently I'm using [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) in the code, which means that currently only **node 14+** version is supported (which may very well be your issue).

Let me know if any of the above fixed your issues, I'll try to push on with the fixes and finishing of the first RC asap. Until then I'm sorry for any inconvenience this may have caused you :)

**Comment by jsimck** [comment] 2021-04-05 12:43
Hi,

if you're still interested in this tool, could you please check if the issue is still present on version 0.1.1? Multiple fixes are on the way for future versions, 0.1.1 was done in haste just to fix major currently existing issues.

**Comment by jsimck** [comment] 2021-05-28 09:40
Should be fixed in latest versions. Closing for now due to inactivity. If the issue occurs again, it'll be reopened.

**Closed by jsimck** 2021-05-28 09:40 UTC
